env:
  CONTAINER_IMAGE_TAG: githubchangeloggenerator/github-changelog-generator:latest
  DOCKER_BUILDX_PLATFORMS: linux/amd64,linux/arm64

name: Build and deploy latest image

on: [push, pull_request]

jobs:
  build:
    name: Lint the codebase, build and test the image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Super-Linter
        uses: github/super-linter@v3.15.5
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build the container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.DOCKER_BUILDX_PLATFORMS }}
          push: false
          tags: ${{ env.CONTAINER_IMAGE_TAG }}
  deploy:
    environment: Docker Hub
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    name: Deploy the container image
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the contaiiner image for all the platforms and eventually push to Docker Hub (latest)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.DOCKER_BUILDX_PLATFORMS }}
          push: true
          tags: ${{ env.CONTAINER_IMAGE_TAG }}
      - name: Test the container image
        shell: bash
        run: docker run ${{ env.CONTAINER_IMAGE_TAG }}
